const express = require('express')
const app = express()
const cors = require('cors')
const bodyParser = require('body-parser')
const users = require('./Router/Users')
const {Authentication,auth} = require('./Router/Authentication')
const rating = require('./Router/Rating')
const tools = require('./tools/tools')
const mysql = require('./tools/mysql')
const { sendMail } = require('./tools/mail')
const crypto = require('crypto')
const Friends = require('./Router/Friends')

tools.init(app, {...mysql,...tools,sendMail,crypto})
app.use(cors())
app.use(express.json())
app.use(bodyParser.json({ limit: '50mb' }))
app.use(bodyParser.urlencoded({ limit: '50mb', extended: true }))
app.use('/Authentication',Authentication)
app.use('/Users', users)
app.use('/Rating',auth, rating)
app.use('/Friends',auth,Friends)
app.get('/image/:image', (req, res) => {
  res.sendFile(`${__dirname}/${req.params.image}`)
})
app.get('/images/:image', (req, res) => {
  res.sendFile(`${__dirname}/images/${req.params.image}`)
})
app.use(tools.handleError)
app.listen(process.env.PORT, () => {
  console.log(`Matcha server app listening at http://localhost:${process.env.PORT}`)
})
// mysql.getFriends(583)
